---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      application: http-simple
  template:
    metadata:
      labels:
        application: http-simple
    spec:
      containers:
      - name: simple
        image: quay.io/gordons/simple-http
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: http-simple
---
